### PR TITLE
Add blog on Shell Command Outputs Truncated in Python

### PR DESCRIPTION
**Pull request by selvait90**

### CODE REVIEW

**Comment by jonjensen** [comment]
@selvait90 Thanks for writing this up!

The solution of setting LANG=C didn't sit right with me, because the column formatting/truncation you're seeing should not be a result of using raw bytes vs. UTF-8 encoding.

So I tried a few things. Take a look at the results of different env settings:

```python
>>> print subprocess.check_output(['dpkg -l | grep libqtcore4'], shell=True)
ii  libqtcore4:amd64                       4:4.8.6+git64-g5dc8b2b+d amd64                    Qt 4 core module

>>> print subprocess.check_output(['dpkg -l | grep libqtcore4'], shell=True, env=None)
ii  libqtcore4:amd64                       4:4.8.6+git64-g5dc8b2b+d amd64                    Qt 4 core module

>>> print subprocess.check_output(['dpkg -l | grep libqtcore4'], shell=True, env={'LANG':'C'})
ii  libqtcore4:amd64                   4:4.8.6+git64-g5dc8b2b+dfsg-3+deb8u1 amd64        Qt 4 core module

>>> print subprocess.check_output(['dpkg -l | grep libqtcore4'], shell=True, env={'LANG':'XXX'})
ii  libqtcore4:amd64                   4:4.8.6+git64-g5dc8b2b+dfsg-3+deb8u1 amd64        Qt 4 core module

>>> print subprocess.check_output(['dpkg -l | grep libqtcore4'], shell=True, env={})
ii  libqtcore4:amd64                   4:4.8.6+git64-g5dc8b2b+dfsg-3+deb8u1 amd64        Qt 4 core module
```
Notice that the default env is None, which is cutting off columns as you experienced. But any LANG setting, including an invalid one, works, as does a totally empty env!

So there really seems to be something else going on here. It turns out, when you have env=None, it really means just use the same environment as the user running the subprocess, which you can see like this:

```python
print subprocess.check_output(['set'], shell=True)
```

Which will print out your environment.

Look through the environment variables as take an educated guess what could be causing this. It turns out to be the terminal's COLUMNS setting causing the output to be cut off.

I can make it happen even more obviously with a simulated very narrow screen:

```python
>>> print subprocess.check_output(['dpkg -l | grep libqtcore4'], shell=True, env={'COLUMNS':'30'})
ii  libqtcore4:amd 4:4.8.6+git6 amd64        Qt 4 core module
```

Do you see what's going on?

Could you please update your blog post to reflect what's really going on here? Thanks!

**Comment by selvait90** [comment]
Posting Emails for reference

I have researched to identify reason by checking with python IRC group and walking through the source code of subprocess library. But still I couldn’t find concrete solution to your question.

I was able spot that there are two different methods called based on env argument to subprocess.check_output. 

when env argument is not passed to subprocess.check_output, os.execv function is called
when env={} argument is passed to subprocess.check_output, os.execve function is called

execv & execve
https://docs.python.org/2/library/os.html#os.execv
os.execv(path, args)
os.execve(path, args, env)¶

But I couldn’t locate the source code of following functions
os.execv
os.execve

from python os library source code to justify the difference. I need identify the source code differences between these two functions. 

Source Code Tracking:
==================

	https://docs.python.org/2/library/subprocess.html
	https://github.com/python/cpython/blob/master/Lib/subprocess.py

	        if env is not None:
	            env_list = []
	            for k, v in env.items():
	                k = os.fsencode(k)
	                if b'=' in k:
	                    raise ValueError("illegal environment variable name")
	                env_list.append(k + b'=' + os.fsencode(v))
	        else:
	            env_list = None  # Use execv instead of execve.

			
		………etc

	            self.pid = _posixsubprocess.fork_exec(
        	            args, executable_list,
                	    close_fds, tuple(sorted(map(int, fds_to_keep))),
	                    cwd, env_list,
        	            p2cread, p2cwrite, c2pread, c2pwrite,
                	    errread, errwrite,
	                    errpipe_read, errpipe_write,
        	            restore_signals, start_new_session, preexec_fn)

		https://github.com/google/python-subprocess32/blob/master/_posixsubprocess.c

		    if (env_list != Py_None) {
		        envp = _PySequence_BytesToCharpArray(env_list);
		        if (!envp)
		            goto cleanup;
		    }


		    for (i = 0; exec_array[i] != NULL; ++i) {
		        const char *executable = exec_array[i];
		        if (envp) {
		            execve(executable, argv, envp);
		        } else {
		            execv(executable, argv);
		        }
		        if (errno != ENOENT && errno != ENOTDIR && saved_errno == 0) {
		            saved_errno = errno;
		        }

Thanks
Selva

**Comment by jonjensen** [comment]
@selvait90 The execv and execve functions are native C functions in the `posix` library. The source is here: https://hg.python.org/cpython/file/2.7/Modules/posixmodule.c#l3142

**Comment by selvait90** [comment]
@jonjensen  The man pages of execv and execve helped to identify the differences of using env={} argument and included those references in blog post with explanation. Please review.

**Comment by jonjensen** [comment]
@selvait90 Ok, this is now live. Thanks!

**Comment by selvait90** [comment]
thank you @jonjensen

**Pull request closed without merging**
