### PR TITLE
Developing on Linux from Windows 10 with Docker and WSL 2

### PR DESCRIPTION
**Pull request by megakevin**
This is a blog post about how to set up a development environment in Windows 10, targeting Linux, using Docker, the Windows Subsystem for Linux and Visual Studio Code. Using PHP as an example.

### CODE REVIEW

**Comment by obnoxiousorc** [comment]
@megakevin This is now live!

**Comment by megakevin** [comment]
> @megakevin This is now live!

Thanks @obnoxiousorc! Just noticed two small issues:

1. Under the "What’s new with WSL 2" subsection, it's been changed to say "However, being a WSL 1 veteran, I’ll a few improvements...". "I’ll a few" looks like it's missing a word. It should say "I'll *mention*" perhaps?

2. Under the "Step 1: Install WSL 2 and Ubuntu" section, the first list item has a weird presentation issue in the live site. Some code that should be multiline is showing up as single line. It looks like this:

image

When it should be looking more like this:

image

I believe that's because the "ps" language is not supported by the blog's markdown renderer? Whatever the case, think you could fix that? I think it's just the "ps" that needs to be removed. So, from

````
```ps
dism.exe /online /enable-feature /featurename:Microsoft-Windows-Subsystem-Linux /all /norestart
dism.exe /online /enable-feature /featurename:VirtualMachinePlatform /all /norestart
```
````

...to just

````
```
dism.exe /online /enable-feature /featurename:Microsoft-Windows-Subsystem-Linux /all /norestart
dism.exe /online /enable-feature /featurename:VirtualMachinePlatform /all /norestart
```
````

**Comment by obnoxiousorc** [comment]
@megakevin Fixed! Thanks for pointing those out.

**Comment by megakevin** [comment]
> @megakevin Fixed! Thanks for pointing those out.

@obnoxiousorc Sweet! Thanks a lot.

**Pull request closed without merging**
