### PR TITLE
Written article about migrating large PostgreSQL tables

### PR DESCRIPTION
**Pull request by lajosarpad**
This is the promised article about our KDHE work

### CODE REVIEW

**Comment by lajosarpad** [comment]
Can this article be published?

**Comment by jonjensen** [comment]
@lajosarpad Unlike some other recent posts this one is waiting on me. Sorry for the delay, but I will get to it soon.

**Comment by lajosarpad** [comment]
> @lajosarpad Unlike some other recent posts this one is waiting on me. Sorry for the delay, but I will get to it soon.

@jonjensen thank you.

**Comment by jonjensen** [comment]
@lajosarpad This is now live. Thanks!

**Pull request closed without merging**
