### PR TITLE
blog09 nov 25

### PR DESCRIPTION
**Pull request by aburayyanjeffry**

### CODE REVIEW

**Comment by aburayyanjeffry** [comment]
Another attempt from my blog09

**Comment by sethjensen1** [comment]
@aburayyanjeffry Could you request reviews as instructed in the wiki: one for the technical side and one for the prose? Then write back here who reviewed it.

**Comment by aburayyanjeffry** [comment]
I've asked for a review at Zulip.

**Comment by sethjensen1** [comment]
@aburayyanjeffry Thanks for asking in Zulip. Since no one responded, could you reach out again, maybe to some individuals? I hear @bharathi3p and @rphipps might be good to ask for a technical review.

**Comment by sethjensen1** [comment]
@aburayyanjeffry This is live, thanks!

**Pull request closed without merging**
