### PR TITLE
Added new post for multi-tenancy architecture

### PR DESCRIPTION
**Pull request by g-soni**
@jonjensen @phinjensen I have created a blog on the multi-tenancy architecture. Please review it and let me know if any changes require. Thanks!

### CODE REVIEW

**Comment by jonjensen** [comment]
@g-soni Thanks! This covers an interesting and relevant topic for our readers.

Could you please make a new version of this image to fix the misspelled word "Tennats" -> "Tenants"? It would also be nice to have all those images as SVGs that are scalable line art, instead of pixelized PNGs.

**Comment by g-soni** [comment]
@jonjensen I will update this, once I finish my current task on TagTeam.

**Comment by g-soni** [comment]
@jonjensen  I have converted the PNGs To SVGs and also fixed the typo. Please have a look at it. Thanks!

**Comment by jonjensen** [comment]
@g-soni Thanks. I took a look at this, and it looks like what you actually did is wrap the PNGs in SVGs, with Base64 encoding. That's not what I was looking for, since they're still bitmapped graphics but this way take even more space.

Take a look at the files in a regular text editor (or just with `cat` or `less`) and you can see they're `data:image/png;base64`.

I was asking for SVGs because those are line art, like Inkscape or Adobe Illustrator would make natively, not bitmapped graphics like the GIMP or Photoshop would make.

What did you make the original graphics in?

**Comment by g-soni** [comment]
Hi @jonjensen, I have added new SVG images. Please have look at it and let me know if any changes still required. Thanks

**Comment by jonjensen** [comment]
Thanks, Gaurav. Those SVG images are much better. There was still a "Tennant" typo, but with the SVG format I was able to fix it myself.

I pulled the SVGs out of the HTML and into their own files, and added a header image (from Flickr, which allows searching for only freely reusable images).

The post is now live!

**Pull request closed without merging**
