### PR TITLE
Add blog post on using Serverless Stack to render and stream PDF

### PR DESCRIPTION
**Pull request by afifsohaili-ep**

### CODE REVIEW

**Comment by jonjensen** [comment]
@afifsohaili-ep Thanks! Great post and very practical and useful example.

Can you point me to where you got the banner image and its license, so we can make sure we have the rights to use that?

**Comment by afifsohaili-ep** [comment]
@jonjensen I got it from Pixabay. Pretty sure we already have the permission. Here's the link: https://pixabay.com/illustrations/cloud-network-website-computer-6515064/

**Comment by jonjensen** [comment]
@afifsohaili-ep That's great. We just always need to have the ownership & permissions documented in the Markdown/HTML source so we have proof later if anyone questions us.

We'll get this published soon!

**Comment by jonjensen** [comment]
This is now live. Thanks!

**Pull request closed without merging**
