### PR TITLE
Find text in a table

### PR DESCRIPTION
**Pull request by eggyknap**
Abusing row types and psql for fun and profit.

### CODE REVIEW

**Comment by jonjensen** [comment]
@eggyknap Thanks! Great to see different approaches and pros/cons.

I'm curious about the `middle_name` of `3e588085-5151-41dd-7592-560163842571` - is that intentional? I thought maybe you would somewhere talk about searching for a UUID in a column it doesn't belong in, but didn't see it. So it feels a little distracting. Could we just leave the `middle_name` blank or make it be a single initial?

**Comment by sethjensen1** [comment]
@jonjensen I did a couple edits on this, added a banner image & comments issue number, etc. I also squashed Josh's commits, and put them in my fork. You can do your edits and make it live from there:

https://github.com/sethjensen1/end-point-blog/tree/find_text_in_a_table

**Comment by eggyknap** [comment]
> @eggyknap Thanks! Great to see different approaches and pros/cons.
> 
> I'm curious about the `middle_name` of `3e588085-5151-41dd-7592-560163842571` - is that intentional? I thought maybe you would somewhere talk about searching for a UUID in a column it doesn't belong in, but didn't see it. So it feels a little distracting. Could we just leave the `middle_name` blank or make it be a single initial?

I agree, it's distracting. It comes from the process I used to create the random data, and there's no reason it couldn't be changed. I changed it to "J" and if I've done it right, this pull request now contains that change along with changes from @sethjensen1 .

**Comment by jonjensen** [comment]
This is live. Thanks, @eggyknap !

**Pull request closed without merging**
