### PR TITLE
Porting SD blog posts

### PR DESCRIPTION
**Pull request by LizFlyntz**
This is a portion of the old SD blog posts - Posts from 1/18/17 "Separate and not equal" and 1/13/16 "Design for the Quotidian"

### CODE REVIEW

**Comment by jonjensen** [comment]
Good to see these coming, @LizFlyntz !

There are a few problems here that I noticed in reviewing it. Let me know if you need help or have questions.

The Markdown files should have suffix `.html.md` not just `.md`. Otherwise they won't be seen by the blog, since they're combined HTML + Markdown.

There are also some far too bloated images:
* 1560 kB: 2016/01/13/design-for-the-quotidian-build-for-the-100-year-flood/100YearFlood.jpg
* 830 kB: 2016/06/27/free-encryption-for-all/LAblog.png
* 275 kB: 2016/11/10/8-simple-steps-to-saner-software-development/bauhausstage.jpg

Those are little header images, so they should probably be roughly ~30 kB JPEG files so as to not hurt the page load time.

`2016/06/27/free-encryption-for-all.html.md` has some weird Frontmatter at the top, perhaps some things that applied to the old blog but not to the new.

**Comment by LizFlyntz** [comment]
@jonjensen Good to know about the markdown appendage.  Will fix!  I'll go through and edit the images, and check any additional images coming from SD posts.  
I didn't finish editing "Free Encryption" into markdown before attempting to merge all my changes.  One thing Jon Allen and I were unable to do is preview images using the "preview" function. Maybe you can help?

**Comment by jonjensen** [comment]
@LizFlyntz Sorry, the preview wasn't designed to show images. (They have a different path when previewed than in production.) The preview was a quick hack meant just to show how the Markdown is looking.

You can get just as far viewing it in the GitHub viewer if you've already committed the work to your fork.

**Comment by LizFlyntz** [comment]
@jonjensen ok good to know! At least I wasn't doing it wrong.  I'll commit another chunk today.

**Comment by jonjensen** [comment]
After some more work, these are now live.

**Comment by LizFlyntz** [comment]
Good to hear.  I’m going to talk to Jon about streamlining this workflow/mitigating my mistakes.

**Pull request closed without merging**
