### PR TITLE
Added a draft of the blog post about using Postgres COPY from Rails

### PR DESCRIPTION
**Pull request by kamilc**
@jonjensen , @phinjensen : Could you please review and let me know what should be corrected and/or if it's good to be published?

Thanks!

### CODE REVIEW

**Comment by kamilc** [comment]
Also, the idea of running a blog this way is **super amazing**!!!! Thank you so much for this transition! :)

**Comment by jonjensen** [comment]
@kamilc Thanks for writing this up! I'll review it soon.

**Comment by jonjensen** [comment]
@kamilc FYI Postgres always checks referential integrity constraints, even when using COPY. The reason INSERT is slower is that it has much more flexibility, which you mentioned later in your post.

I updated this and some other minor things so we don't have people thinking COPY circumvents referential integrity:

https://github.com/EndPointCorp/end-point-blog/commit/c3cdc40278c1e97c236f78ba5ed73890c6de48fe

@phinjensen I also changed the headers to be H3, since H2 is the title header size.

**Comment by kamilc** [comment]
@jonjensen That's good to learn - Thank you :)

**Pull request merged**
