### PR TITLE
Python Concurrency

### PR DESCRIPTION
**Pull request by mvollrath**
asyncio for threading users

### CODE REVIEW

**Comment by mvollrath** [comment]
Pending review.

**Comment by mvollrath** [comment]
Reviewed by Jeff Laughlin.

**Comment by jonjensen** [comment]
@mvollrath Great article! Nicely illustrates the jitter, too.

You're all ready for it to be published now?

**Comment by mvollrath** [comment]
Yep, ready to fly.

**Comment by mvollrath** [comment]
@jonjensen revising `asyncio.wait()` usage due to a Python 3.9 deprecation..

**Comment by mvollrath** [comment]
Ready now.

**Comment by jonjensen** [comment]
@mvollrath Great article. Thanks!

**Pull request closed without merging**
