### PR TITLE
 Blog post on how to write End to End and Component tests with Cypress in Vue

### PR DESCRIPTION
**Pull request by Mloweedgar**
**Blog post reviwers:**
This blog post has already been reviewed by:

- @darius-endpoint 
- @NicholasPiano 

Please let me know if something needs to be improved/changed. Thanks!

### CODE REVIEW

**Comment by NicholasPiano** [comment]
@Mloweedgar I have gone through the steps for setting up and running tests. Everything works perfectly!

One thing to add: during the setup for E2E tests, it automatically creates Cypress config files. Perhaps mention this step in the instructions so the reader is not confused.

**Comment by Mloweedgar** [comment]
Thank you very much @NicholasPiano  for taking time to review my blog and providing feedback. 

I have updated the blog to address your feedback please take a look to see if I have properly address your feedback.

**Comment by jonjensen** [comment]
@Mloweedgar @NicholasPiano Are you both ok with this blog post now as it is?

**Comment by Mloweedgar** [comment]
@jonjensen I am okay with the blog post unless if there is any further feedback.

**Comment by jonjensen** [comment]
@sethjensen1 Ok, it's all yours!

**Comment by jonjensen** [comment]
@Mloweedgar Great article. This blog post is now live. Thanks!

**Comment by Mloweedgar** [comment]
Thank you very much @jonjensen !

**Pull request closed without merging**
