### PR TITLE
Added Active Storage blog

### PR DESCRIPTION
**Pull request by g-soni**
@jonjensen @phinjensen I have created a blog on the Active Storage. Please review it and let me know if any changes require. Thanks!

### CODE REVIEW

**Comment by stephskardal** [comment]
In the first paragraph s/uploading/uploaded/.

Question on this @g-soni - Is this meant to work in parallel with file attachment like CarrierWave or Paperclip, or is it meant to replace them? It looks like it's the latter. Can you comment that in your post?

**Comment by jonjensen** [comment]
@g-soni I think Steph asks good questions here. Can you comment in your article?

**Comment by g-soni** [comment]
@stephskardal yes it is the replacement for the CarrierWave or Paperclip with support for minimagik and rmagick. Active storage is a built-in feature for rails 5.2.

@jonjensen I will update this in my article once I finish my current task on TagTeam

**Comment by g-soni** [comment]
@jonjensen I have updated the active storage blog. Please have a look at it and let me know. Thanks!

**Comment by jonjensen** [comment]
@g-soni Thanks for writing this. It is now live!

**Pull request closed without merging**
