### PR TITLE
Added two new blog posts 2019\03\05 and 2019\03\07

### PR DESCRIPTION
**Pull request by juanpabloventoso**
Added new blog post "running-magento-2-windows-xampp.html"

### CODE REVIEW

**Comment by lajosarpad** [comment]
For picture I was thinking something like https://3c1703fe8d.site.internapcdn.net/newman/gfx/news/hires/2019/chancesforli.jpg

but I'm not sure we are free to use this.

**Comment by juanpabloventoso** [comment]
> For picture I was thinking something like https://3c1703fe8d.site.internapcdn.net/newman/gfx/news/hires/2019/chancesforli.jpg
> 
> but I'm not sure we are free to use this.

For a Magento 2 installation post? That would be original LOL

**Comment by lajosarpad** [comment]
@juanpabloventoso 

I have written an article as well, mine was about estimation. The picture I suggested was meant for the article written by me

**Comment by juanpabloventoso** [comment]
> @juanpabloventoso
> 
> I have written an article as well, mine was about estimation. The picture I suggested was meant for the article written by me

Oops sorry, didn't know that there might be more than one author within the same pull request...

**Comment by lajosarpad** [comment]
@juanpabloventoso it was my mistake, sorry about that.

**Comment by juanpabloventoso** [comment]
No worries!

**Comment by jonjensen** [comment]
@juanpabloventoso Thank you. Nice articles!

For the Leaflet default map tiles, I used the new https URL that doesn't have a `{s}` sharded subdomain, since so many sites are on HTTPS and will get mixed-content errors with a plain http URL, and HTTP/2 does better without sharding. That's what we're using for endpoint.com, but let me know if you need it changed back for some reason, or if you see any other problems. Thanks!

**Comment by juanpabloventoso** [comment]
Sounds good Jon, thank you!

**Pull request closed without merging**
