### PR TITLE
Two blog's draft to be reviewed

### PR DESCRIPTION
**Pull request by raden**

### CODE REVIEW

**Comment by sethjensen1** [comment]
@jonjensen I copy-edited the post about EndeavourOS, it's ready for you in my fork. Please review and then I can do a final round, get an image, make a comment issue, and publish. (Maybe make a PR into my fork? That might be easiest)

https://github.com/sethjensen1/end-point-blog/tree/najmi-endeavouros

**Comment by jonjensen** [comment]
@sethjensen1 Looks good.

Most importantly: It would be really helpful to have at least a one-line explanation of why this distro exists. How does it differ from Arch? [Its about page](https://endeavouros.com) says some things, but kind of assumes we know why the defunct Antergos distro existed, and how it differed. I can't see why I would use this instead of Arch.

Minor nits:

> the hundreds (or thousands) of Linux distros out there

I think it's plenty to say "hundreds" here.

Remember to add the zero-width break after `/` where needed.

FWIW, these could be one line:

```
systemctl enable cronie
systemctl enable bluetooth
```

as:

```
systemctl enable cronie bluetooth
```

And that only enables them on next boot, so add `--now` to start now as well.

`s/go language/Go language/`

`s/sshaskpass/ssh-askpass/` when talking about it generically, though not the specific Arch package from yay which probably lacks the `-`.

**Comment by sethjensen1** [comment]
@raden Your EndeavourOS post is live. @obnoxiousorc is working on the post about Unix tools.

**Comment by sethjensen1** [comment]
Moving this over to https://github.com/EndPointCorp/end-point-blog/pull/1989 for the remaining post about Unix Tools.

**Pull request closed without merging**
